Proofreading of documentation by an analyst.
smartworldteam/egal-docs pull request #17
Opened 2021-05-26 05:00 UTC by MakhorinDmitriy

Первичная вычитка документации аналитиком. Перефразировал, упрощал.
Посмотрите как вам.

2021-05-26 10:40 UTC, Yulya-Yu commented on client/actions.md
> +    <!-- не совсем понятно зачем в getAll название модели -->
название модели не нужно

2021-05-26 10:41 UTC, Yulya-Yu commented on client/actions.md
> +10. Action deleteMany: удаление нескольких моделей.
неправильно использовать 'моделей',  удаляются сущности (как было изначально написано)

2021-05-26 10:43 UTC, Yulya-Yu commented on client/actions.md
> +11. Action updateManyWithFilter: обновление нескольких отфильтрованных сущностей.
слово "отфильтрованных" не несет нужный смысл, непонятно, что имеется ввиду.
Настаиваю на своей формулировке: "на основе указанных фильтров".

2021-05-26 10:43 UTC, Yulya-Yu commented on client/actions.md
> +12. Action deleteManyWithFilter: удаление нескольких отфильтрованных сущностей
слово "отфильтрованных" не несет нужный смысл, непонятно, что имеется ввиду.
Настаиваю на своей формулировке: "на основе указанных фильтров".

2021-05-26 10:45 UTC, Yulya-Yu commented on client/cookbook/components.md
> +1) В `mounted()` инициализируем модель и активируем слушателя для получения данных:
"ставить" или "устанавливать" слушатель - устоявшееся словосочетание. Использовать "активируем" неправильно и не понятно.

2021-05-26 10:46 UTC, Yulya-Yu commented on client/example_auth.md
> +3) Подписываемся на Observer модели и слушаем получаемые события:
думаю надо оставить предыдущую формулировку, иначе как-то непонятно, что к чему относится

2021-05-26 10:47 UTC, Yulya-Yu commented on client/examples.md
> +Для использования экшена отдельно от модели инициализируется новый экземпляр класса с указанием параметров.
"нужные параметры"

2021-05-26 10:49 UTC, Yulya-Yu commented on client/examples.md
> +запрос getItem похож на getItems, но дополнительно к параметрам указывается id сущности с помощью метода setId()
**обязательно** указывается id сущности

2021-05-26 10:50 UTC, Yulya-Yu commented on client/examples.md
> +в переменных *orders* и *filter* хранятся параметры передаваемые с запросом. Вид параметров должен быть таким, как указано.
после параметры не нужна запятая?

2021-05-26 10:52 UTC, Yulya-Yu commented on client/intro.md
> +- создаются гибкие пользовательские интерфейсы
звучит неправильно.
Идея в том, что фреймворк ПОМОГАЕТ РАЗРАБОТЧИКУ

Сейчас не понятно каким образом выполняются задачи и создаются интерфейсы. Как-будто они сами это как-то делают.

2021-05-26 10:53 UTC, Yulya-Yu commented on client/intro.md
> +Фреймворк полностью берет на себя задачи по формированию кастомизируемых запросов к серверу, используя несколько механизмов связи на выбор: Axios (API) и связь по rabbitMQ (сокетам).
"правильных" нужное слово. Правильных по отношению к бэк части фреймворка. А не просто правильных, в смысле не неправильных

2021-05-26 10:54 UTC, Yulya-Yu commented on client/model.md
> +В ней есть вспомогательные методы для получения части информации о модели (например, запрос только списка релейшенов модели, список полей, доступные экшены, нужные поля и т.д.).
Настаиваю на своей формулировке. Эта звучит слишком непрофессионально и по-детски.

2021-05-26 10:56 UTC, Yulya-Yu commented on client/model.md
>  14. getSpecificFields:
можно добавить:
getSpecificFields - получение только указанных пользователем полей.

2021-05-26 10:57 UTC, Yulya-Yu commented on client/observer.md
> +Класс Observer можно использовать внутри приложения для внутренних операций.
настаиваю на своей формулировке, новая звучит как-то неполно и не четко.

2021-05-26 10:57 UTC, Yulya-Yu commented on client/observer.md
> +1) Сначала создадим класс:
вернуть слова-маркеры

2021-05-26 10:57 UTC, Yulya-Yu commented on client/observer.md
> +// создадим метод для класса
вернуть слова-маркеры

2021-05-26 10:57 UTC, Yulya-Yu commented on client/observer.md
> +2) В компоненте при вызове метода инициализируем экземпляр класса Toaster и вызываем его метод success():
вернуть слова-маркеры и запятые

2021-05-26 10:58 UTC, Yulya-Yu commented on client/observer.md
> +3) В компоненте подписываемся на события Toaster
вернуть слова-маркеры

2021-05-26 10:58 UTC, Yulya-Yu commented on client/observer.md
> +        // выполняем действия
вернуть слова-маркеры

2021-05-26 10:58 UTC, Yulya-Yu commented on client/start.md
> +Далее в нужном файле импортировать классы для работы.
какие классы для работы?

2021-05-26 10:59 UTC, Yulya-Yu commented on client/start.md
> +Для привязки Observer к модели передается название модели в качестве аргумента при подписке на события:
неправильно и непонятно звучит.
куда что передается?
настаиваю на своей формулировке

2021-05-26 11:00 UTC, Yulya-Yu commented on client/start.md
> + Rогда в сокет приходит сообщение для указанной модели, его можно будет получить в любом месте приложения.
настаиваю на своей формулировке, более развернутая

2021-05-31 04:21 UTC, MakhorinDmitriy commented on client/actions.md
> +    <!-- не совсем понятно зачем в getAll название модели -->
Убрал

2021-05-31 04:22 UTC, MakhorinDmitriy commented on client/actions.md
> +10. Action deleteMany: удаление нескольких моделей.
Исправил

2021-05-31 04:24 UTC, MakhorinDmitriy commented on client/actions.md
> +11. Action updateManyWithFilter: обновление нескольких отфильтрованных сущностей.
Сделал формулировку "на основе выбранных фильтров"

2021-05-31 04:24 UTC, MakhorinDmitriy commented on client/actions.md
> +12. Action deleteManyWithFilter: удаление нескольких отфильтрованных сущностей
Сделал формулировку "на основе выбранных фильтров"

2021-05-31 04:25 UTC, MakhorinDmitriy commented on client/cookbook/components.md
> +1) В `mounted()` инициализируем модель и активируем слушателя для получения данных:
Изменил формулировку на "устанавливаем слушателя"

2021-05-31 04:27 UTC, MakhorinDmitriy commented on client/example_auth.md
> +3) Подписываемся на Observer модели и слушаем получаемые события:
Поменял формулировку на "Подписываемся на Observer модели и слушаем получаемые им события:"

2021-05-31 04:28 UTC, MakhorinDmitriy commented on client/examples.md
> +Для использования экшена отдельно от модели инициализируется новый экземпляр класса с указанием параметров.
Сделал

2021-05-31 04:30 UTC, MakhorinDmitriy commented on client/examples.md
> +В переменных *orders* и *filter* хранятся параметры передаваемые с запросом. Вид параметров всегда должен быть таким как указано.
Сделал формулировку "Вид параметров стандартизован и должен быть таким как указано."

2021-05-31 04:30 UTC, MakhorinDmitriy commented on client/examples.md
> +запрос getItem похож на getItems, но дополнительно к параметрам указывается id сущности с помощью метода setId()
Сделал

2021-05-31 04:34 UTC, MakhorinDmitriy commented on client/examples.md
> +в переменных *orders* и *filter* хранятся параметры передаваемые с запросом. Вид параметров должен быть таким, как указано.
Поправил

2021-05-31 04:35 UTC, MakhorinDmitriy commented on client/intro.md
> +- создаются гибкие пользовательские интерфейсы
Изменил формулировку на 

Фреймворк помогает разработчику: 
- выполнять рутинные задачи быстрее
- создавать гибкие пользовательские интерфейсы

2021-05-31 04:36 UTC, MakhorinDmitriy commented on client/intro.md
> +Фреймворк полностью берет на себя задачи по формированию кастомизируемых запросов к серверу, используя несколько механизмов связи на выбор: Axios (API) и связь по rabbitMQ (сокетам).
Изменил формулировку на "по формированию верных кастомизируемых запросов к серверу"

2021-05-31 04:39 UTC, MakhorinDmitriy commented on client/model.md
> +В ней есть вспомогательные методы для получения части информации о модели (например, запрос только списка релейшенов модели, список полей, доступные экшены, нужные поля и т.д.).
Сделал формулировку:

Модель используется для вызова действий и хранения информации. 

Существуют вспомогательные методы для получения части информации о модели (например, запрос только списка отношений модели, доступных действий, набора полей и т.д.).

2021-05-31 04:39 UTC, MakhorinDmitriy commented on client/model.md
>  14. getSpecificFields:
Добавил

2021-05-31 04:41 UTC, MakhorinDmitriy commented on client/observer.md
> +Класс Observer можно использовать внутри приложения для внутренних операций.
Сделал формулировку "Класс Observer можно использовать внутри приложения для выполнения внутренних операций. "

2021-05-31 04:41 UTC, MakhorinDmitriy commented on client/observer.md
> +1) Сначала создадим класс:
Вернул

2021-05-31 04:42 UTC, MakhorinDmitriy commented on client/observer.md
> +// создадим метод для класса
Оставил новый вариант, мне кажется здесь все-таки не обязателен "нужный"

2021-05-31 04:43 UTC, MakhorinDmitriy commented on client/observer.md
> +2) В компоненте при вызове метода инициализируем экземпляр класса Toaster и вызываем его метод success():
Сделал формулировку "В компоненте при вызове этого метода инициализируем экземпляр класса Toaster и вызываем его метод success():"

2021-05-31 04:43 UTC, MakhorinDmitriy commented on client/observer.md
> +3) В компоненте подписываемся на события Toaster
Вернул

2021-05-31 04:43 UTC, MakhorinDmitriy commented on client/observer.md
> +        // выполняем действия
Оставил новый вариант, мне кажется здесь все-таки не обязателен "нужный"

2021-05-31 04:49 UTC, MakhorinDmitriy commented on client/start.md
> +Далее в нужном файле импортировать классы для работы.
Оставил новый вариант, мне кажется здесь все-таки не обязателен "нужный", здесь уже есть пояснение, что это не просто классы, а классы для работы

2021-05-31 04:50 UTC, MakhorinDmitriy commented on client/start.md
> +Для привязки Observer к модели передается название модели в качестве аргумента при подписке на события:
Сделал формулировку "Для привязки Observer к модели нужно передать название модели в качестве аргумента при подписке на события:"

2021-05-31 04:53 UTC, MakhorinDmitriy commented on client/start.md
> + Rогда в сокет приходит сообщение для указанной модели, его можно будет получить в любом месте приложения.
Сейчас формулировка такая:

Когда в сокет приходит сообщение для указанной модели, его можно будет получить в любом месте приложения. 
Вместе с сообщением приходит название отработавшего действия.
 
Мне кажется смысл никак не теряется

2021-05-31 08:25 UTC, rollsover requested changes
Половину только проверил, уже сгорел с не правильных времен. Очень много замечани, см. комменты

2021-05-31 08:25 UTC, rollsover commented on getting_started/configuration.md
> +| PROJECT_NAME          | Название проекта. Подставляется  <!-- Подставляется что? -->                                          | Строка                       |
Убрать коммент, а также слово `Подставляется`

2021-05-31 08:25 UTC, rollsover commented on getting_started/configuration.md
> +| DATABASE_PORT         | Список баз данных для других сервисов в проекте.         | Целое не отрицательное число |
Вертай

2021-05-31 08:25 UTC, rollsover commented on getting_started/first_endpoint.md
> +После выполнения команды в директории `app\Models` создается
именно `создастся`.

2021-05-31 08:25 UTC, rollsover commented on getting_started/first_endpoint.md
> +4. Генерируется миграция
Вертай обратно

2021-05-31 08:25 UTC, rollsover commented on getting_started/first_endpoint.md
> +создается файл.
вертай

2021-05-31 08:25 UTC, rollsover commented on getting_started/first_endpoint.md
> +6. Запускается/перезапускается демон сервиса
Вертай

2021-05-31 08:25 UTC, rollsover commented on getting_started/first_endpoint.md
> +7. Вызывается нужный Endpoint с помощью Web Service, либо с помощью
Вертай

2021-05-31 08:25 UTC, rollsover commented on getting_started/install.md
> +Создание структуры репозиториев для разворачивания Egal Server.
Вертай, вообще не о том написано. Прочитай нормально что было написано ранее

2021-05-31 08:25 UTC, rollsover commented on getting_started/install.md
> +1. Создание нового репозитория (в дальнейшем - Develop)
Да, ***, инструкции вообще видел как люди пишут?

2021-05-31 08:25 UTC, rollsover commented on getting_started/install.md
> +1. Создание нового репозитория (в дальнейшем - Develop)
Полностью файл вертай

2021-05-31 08:25 UTC, rollsover commented on getting_started/install.md
> +    > Если ответ не получен - нужно ждать полного старта сервисов.
Дождаться

2021-05-31 08:25 UTC, rollsover commented on getting_started/install.md
> +    > Если в течение 1 минуты сервисы не запустились — проверяются docker-compose logs.
Проверяйте

2021-05-31 08:25 UTC, rollsover commented on getting_started/install.md
> +1. Дополнение `docker-compose.yml` в секции `services` сервисами:
Опять не то время во всем файле

2021-05-31 08:25 UTC, rollsover commented on getting_started/install.md
> +    > Если выводится ошибку `Could not find package egal/egal with stability stable.` - выполняется следующая команда:
`ошибка` тогда уже

2021-05-31 08:25 UTC, rollsover commented on getting_started/install.md
> +2. Дополнение `docker-compose.yml` в секции `services` сервисами:
Вертай

2021-05-31 08:25 UTC, rollsover commented on getting_started/install.md
> +5. Перевод `monolit-service` директорию в git submodule Develop репозитория:
Все равно не то слово

2021-05-31 08:25 UTC, rollsover commented on getting_started/install.md
> +    1. Перемещение кодовой базы во временную директорию:
Опять же весь файл вертай

2021-06-01 09:30 UTC, Yulya-Yu commented on client/actions.md
> +11. Action updateManyWithFilter: обновление нескольких отфильтрованных сущностей.
почему "выбранных"? это не правильно.

2021-06-01 09:30 UTC, Yulya-Yu commented on client/actions.md
> +12. Action deleteManyWithFilter: удаление нескольких отфильтрованных сущностей
почему "выбранных"? это не правильно.

2021-06-01 09:31 UTC, Yulya-Yu commented on client/cookbook/components.md
> +1) В `mounted()` инициализируем модель и активируем слушателя для получения данных:
"слушате**ля**"?  "ставить" или "устанавливать" слушатель - устоявшееся словосочетание.

2021-06-01 09:32 UTC, Yulya-Yu commented on client/example_auth.md
> +3) Подписываемся на Observer модели и слушаем получаемые события:
обзерверы могут быть у любой модели. О какой модели тут речь?

2021-06-01 10:29 UTC, MakhorinDmitriy commented on client/actions.md
> +11. Action updateManyWithFilter: обновление нескольких отфильтрованных сущностей.
Сделал "указанных"

2021-06-01 10:29 UTC, MakhorinDmitriy commented on client/actions.md
> +12. Action deleteManyWithFilter: удаление нескольких отфильтрованных сущностей
Сделал "указанных"

2021-06-01 10:30 UTC, MakhorinDmitriy commented on client/cookbook/components.md
> +1) В `mounted()` инициализируем модель и активируем слушателя для получения данных:
Сделал "устанавливаем слушатель"

2021-06-01 10:31 UTC, MakhorinDmitriy commented on client/example_auth.md
> +3) Подписываемся на Observer модели и слушаем получаемые события:
Вернул изначальную формулировку

2021-06-02 02:55 UTC, MakhorinDmitriy commented on _glossary.md
> +> В Egal смотри [документацию](server/crud/index.md).
Не совсем понимаю о чем ты, я не удалял ссылку

2021-06-02 02:56 UTC, MakhorinDmitriy commented on _glossary.md
> +##### Действия
Для того, чтобы уйти от англицизмов по тексту документации - вместо "экшенов" используются "действия", вместо "филдов" - поля и т.д.

2021-06-02 02:56 UTC, MakhorinDmitriy commented on _glossary.md
> +##### Слушатель
Сделано, чтобы уйти от англицизмов по тексту документации - вместо "экшенов" используются "действия", вместо "филдов" - поля и т.д.

2021-06-02 03:33 UTC, MakhorinDmitriy commented on cicd/gitlab_ci/index.md
> +> Альтернатива OCB Workflow см. [Как настроить свой Git Workflow](#Как-настроить-свой-git-workflow).
Изменил формулировку на

В Egal можно использовать как встроенную систему ветвления - One Code Base Workflow
(OCB Workflow), так и [настроить ее самостоятельно](#Как-настроить-свой-git-workflow).

2021-06-02 04:28 UTC, MakhorinDmitriy commented on client/intro.md
> +- создаются гибкие пользовательские интерфейсы
Вернул изначальный вид

2021-06-02 04:29 UTC, MakhorinDmitriy commented on client/intro.md
> +Фреймворк полностью берет на себя задачи по формированию кастомизируемых запросов к серверу, используя несколько механизмов связи на выбор: Axios (API) и связь по rabbitMQ (сокетам).
Вернул изначальную формулировку

2021-06-02 04:31 UTC, MakhorinDmitriy commented on client/model.md
> +В ней есть вспомогательные методы для получения части информации о модели (например, запрос только списка релейшенов модели, список полей, доступные экшены, нужные поля и т.д.).
Вернул изначальную формулировку. Заменил только англицизмы - экшены на действия и т.д.

2021-06-02 04:32 UTC, MakhorinDmitriy commented on client/observer.md
> +Класс Observer можно использовать внутри приложения для внутренних операций.
Вернул изначальную формулировку.

2021-06-02 04:32 UTC, MakhorinDmitriy commented on client/observer.md
> +// создадим метод для класса
Вернул изначальную формулировку.

2021-06-02 04:32 UTC, MakhorinDmitriy commented on client/observer.md
> +2) В компоненте при вызове метода инициализируем экземпляр класса Toaster и вызываем его метод success():
Вернул изначальную формулировку.

2021-06-02 04:33 UTC, MakhorinDmitriy commented on client/observer.md
> +        // выполняем действия
Вернул изначальную формулировку.

2021-06-02 04:33 UTC, MakhorinDmitriy commented on client/start.md
> +Далее в нужном файле импортировать классы для работы.
Вернул изначальную формулировку.

2021-06-02 04:34 UTC, MakhorinDmitriy commented on client/start.md
> +Для привязки Observer к модели передается название модели в качестве аргумента при подписке на события:
Вернул изначальную формулировку.

2021-06-02 04:35 UTC, MakhorinDmitriy commented on client/start.md
> + Rогда в сокет приходит сообщение для указанной модели, его можно будет получить в любом месте приложения.
Вернул изначальную формулировку, только заменил "экшен" на "действие"

2021-06-02 04:36 UTC, MakhorinDmitriy commented on cicd/gitlab_ci/index.md
> +## Как это работает
Вернул

2021-06-02 04:37 UTC, MakhorinDmitriy commented on cicd/gitlab_ci/index.md
> +<!-- Здесь точно Release Candidate для "release"? -->
Сделал

2021-06-02 04:47 UTC, MakhorinDmitriy commented on cicd/gitlab_ci/index.md
> +При единой кодовой базе будут однообразными и все сборки проекта на
Переформулировал на:

При единой кодовой базе однообразны и все сборки проекта на
всех версиях серверов. Это позволяетт экономить время на
проверке одинаковых функций на разных серверах. Также в этой схеме
build приложения делается один раз на все типы серверов, что
оптимизирует общее время deploy, и позволяет не задумываться о разных
окружениях частей приложения на разных серверах.

2021-06-02 05:01 UTC, MakhorinDmitriy commented on cicd/gitlab_ci/index.md
> +# Дополнение задания deploy monolit-service.
Заменил на предлагаемую формулировку "Дополнение CI заданием deploy monolit-service"

2021-06-02 05:11 UTC, MakhorinDmitriy commented on client/actions.md
> +<!-- неочевидно где в экшене описаны используемые фильтры -->
Переговорил с Юлей, она попросила оставить, чтобы потом поправить.

2021-06-02 05:24 UTC, MakhorinDmitriy commented on client/auth.md
> +Этапы авторизации в системе:
Думаю, что да
С Юлей согласовал

2021-06-02 05:25 UTC, MakhorinDmitriy commented on client/auth.md
> +Если UST токен просрочен, нужно проверить действителен ли UMT токен и, используя его, заново запрашивается UST токен.
Сделал "запросить"

2021-06-02 05:26 UTC, MakhorinDmitriy commented on concepts/architecture.md
> -* Возможность полностью контролировать и эффективно распределять
Вернул "полностью"

2021-06-02 05:28 UTC, MakhorinDmitriy commented on concepts/architecture.md
> +Сообщения событий генерируются и обрабатываются любой частью
Вернул "могут"

2021-06-02 05:34 UTC, MakhorinDmitriy commented on concepts/architecture.md
> +приложения. Сообщения обрабатываются если есть
Сделал формулировку "Сообщения обрабатываются только если есть
доступ к ним и инструкция по их обработке."

2021-06-02 05:36 UTC, MakhorinDmitriy commented on concepts/request_to_server_lifecycle.md
> +> Параметры уникальных действия запрашиваются у разработчиков Egal.
Вернул изначальную версию (убрал "Egal")

2021-06-02 05:38 UTC, MakhorinDmitriy commented on concepts/request_to_server_lifecycle.md
> +Перед отправкой подготавливается структуру получения ответных
Вернул обратно

2021-06-02 06:43 UTC, MakhorinDmitriy commented on concepts/request_to_server_lifecycle.md
> +> привязанными к нему очередями. Т.е. если у балансера 3 привязанных очереди, сообщение отправляется в одну из них.
Расписал "то есть"

2021-06-02 06:45 UTC, MakhorinDmitriy commented on concepts/request_to_server_lifecycle.md
> +   * В случае успешного вызова действия формируется сообщение
Не нужно

2021-06-02 06:46 UTC, MakhorinDmitriy commented on concepts/request_to_server_lifecycle.md
> +[отправке запроса](#Отправка-запроса) приходят сообщения
Вернул "будут приходить"

2021-06-02 06:52 UTC, MakhorinDmitriy commented on getting_started/configuration.md
> +контейнеров с описанием переменных окружения.
Сделал формулировку

В разделе описана конфигурация сервисов и ключевых
контейнеров с описанием основных переменных окружения.

2021-06-02 06:59 UTC, MakhorinDmitriy commented on getting_started/configuration.md
> +* в файле docker-compose.yml для конкретного сервиса.
Сделал

"в файле docker-compose.yml в блоке enviroment сервиса"

2021-06-02 07:01 UTC, Yulya-Yu commented on client/actions.md
> +<!-- неочевидно где в экшене описаны используемые фильтры -->
я попросила убрать коммент и сказала, что поправлю

2021-06-02 07:03 UTC, MakhorinDmitriy commented on getting_started/configuration.md
> +> Если значение переменной (в т.ч. по умолчанию)
Сделал

2021-06-02 07:06 UTC, MakhorinDmitriy commented on getting_started/configuration.md
>  | DB_CONNECTION               | Тип драйвера для подключения к БД.                                                                     | pgsql, mysql, sqlite                         |
Сделал расшифровку "БД" в глоссарии

2021-06-02 07:08 UTC, MakhorinDmitriy commented on getting_started/configuration.md
> +| PROJECT_NAME          | Название проекта. Подставляется  <!-- Подставляется что? -->                                          | Строка                       |
Сделал

2021-06-02 07:10 UTC, MakhorinDmitriy commented on getting_started/configuration.md
> +| DATABASE_PORT         | Список баз данных для других сервисов в проекте.         | Целое не отрицательное число |
Сделал

2021-06-02 07:11 UTC, MakhorinDmitriy commented on getting_started/first_endpoint.md
> +После выполнения команды в директории `app\Models` создается
Сделал

2021-06-02 07:14 UTC, MakhorinDmitriy commented on getting_started/first_endpoint.md
> +4. Генерируется миграция
Сделал

3. Откройте сгенерированный файл модели и опишите метаданные сущности (см. [документацию](/server/metadata.md))
4. Сгенерируйте миграцию

2021-06-02 07:15 UTC, MakhorinDmitriy commented on getting_started/first_endpoint.md
> +создается файл.
Сделал

После выполнения этой команды в директории `database/migrations`
создастся файл.

2021-06-02 07:16 UTC, MakhorinDmitriy commented on getting_started/first_endpoint.md
> +6. Запускается/перезапускается демон сервиса
Сделал

2021-06-02 07:16 UTC, MakhorinDmitriy commented on getting_started/first_endpoint.md
> +7. Вызывается нужный Endpoint с помощью Web Service, либо с помощью
Сделал

2021-06-02 07:17 UTC, MakhorinDmitriy commented on getting_started/install.md
> +Создание структуры репозиториев для разворачивания Egal Server.
Сделал

Создадим структуру репозиториев, которая поможет легко и быстро разворачивать Egal Server.

2021-06-02 07:24 UTC, MakhorinDmitriy commented on getting_started/install.md
> +    > Если ответ не получен - нужно ждать полного старта сервисов.
Сделал

2021-06-02 07:25 UTC, MakhorinDmitriy commented on getting_started/install.md
> +    > Если в течение 1 минуты сервисы не запустились — проверяются docker-compose logs.
Сделал "проверьте"

2021-06-02 07:31 UTC, MakhorinDmitriy commented on getting_started/install.md
> +    > Если выводится ошибку `Could not find package egal/egal with stability stable.` - выполняется следующая команда:
Сделал

2021-06-02 07:33 UTC, MakhorinDmitriy commented on getting_started/install.md
> +2. Дополнение `docker-compose.yml` в секции `services` сервисами:
Сделал

2021-06-02 07:36 UTC, MakhorinDmitriy commented on getting_started/install.md
> +    1. Перемещение кодовой базы во временную директорию:
Сделал

2021-06-03 04:32 UTC, rollsover requested changes

2021-06-03 04:32 UTC, rollsover commented on server/ways_to_start_and_stop_service.md
> +<!-- Есть пять разных способ запуска слушателя сервиса. Может стоит пояснить когда каждый из них используется/какой из них лучше? -->
Убрать

2021-06-03 04:39 UTC, MakhorinDmitriy commented on _glossary.md
> +> В Egal смотри [документацию](server/crud/index.md).
Решили убрать ссылку вообще

2021-06-03 04:41 UTC, MakhorinDmitriy commented on cicd/gitlab_ci/index.md
> +│   ├── docker-compose.deploy.yml # Deploy Compose файл дополняет общий Compose файл для Develop, Stage и Production версий приложения.
Поправил

2021-06-03 04:41 UTC, MakhorinDmitriy commented on cicd/gitlab_ci/index.md
> +│       ├── ... # Дополнительные файлы для build proxy
Поправил

2021-06-03 04:41 UTC, MakhorinDmitriy commented on cicd/gitlab_ci/index.md
> +│   ├── Dockerfile # Файл build сервиса должен полностью подготовить контейнер. При развороте он запустит сервис.
Поправил

2021-06-03 04:44 UTC, MakhorinDmitriy commented on client/actions.md
> +6. Action getMetadata: получение метадаты модели.
Исправил на "метаданных"

2021-06-03 04:44 UTC, MakhorinDmitriy commented on client/actions.md
> +<!-- неочевидно где в экшене описаны используемые фильтры -->
Убрал

2021-06-03 04:46 UTC, MakhorinDmitriy commented on getting_started/install.md
> +5. Перевод `monolit-service` директорию в git submodule Develop репозитория:
Изменил на "преобразуем"

2021-06-03 05:07 UTC, MakhorinDmitriy commented on server/ways_to_start_and_stop_service.md
> +<!-- Есть пять разных способ запуска слушателя сервиса. Может стоит пояснить когда каждый из них используется/какой из них лучше? -->
Сделал

2021-06-04 13:57 UTC, l-max commented on getting_started/configuration.md
>  | DB_CONNECTION               | Тип драйвера для подключения к БД.                                                                     | pgsql, mysql, sqlite                         |
заменил везде на расшифровку

2021-06-04 13:59 UTC, l-max commented on getting_started/configuration.md
> +| RABBITMQ_PLUGINS            | Активируемые плагины RabbitMQ. Перечисляются через запятую. | Строка             |
fixed ;)

2021-06-04 14:02 UTC, l-max commented on getting_started/configuration.md
> +| RABBITMQ_MANAGER_PORT | Активируемые плагины RabbitMQ. Перечисляются через запятую. | Целое не отрицательное число |
fixed

2021-06-04 16:35 UTC, l-max approved these changes

2021-06-04 16:54 UTC, l-max commented
Чтото вернул как было, чтото подправил.
Были опечатки много где.

2021-06-07 06:28 UTC, rollsover approved these changes
Проверено. Исправлен code style, грамматические ошибки и опечатки

2021-06-07 06:32 UTC, Yulya-Yu approved these changes
исправления по фронту вычитала, просмотрю еще раз когда буду дополнять документацию.

2021-06-07 06:40 UTC, merged